### ISSUE TITLE
Facets for landing page

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/taxon-overflow#1]
Add support for facets on the left hand side (or right).
Things to facet include:

- tags
- question type

![screenshot 2015-02-27 11 25 15](https://cloud.githubusercontent.com/assets/444897/6405105/6cf349ca-be73-11e4-9a1c-1864fe4a7f0e.png)

**Comment by aruizca** [comment]
FYI The [facets mechanism](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-facets.html) has been deprecated. I will use "aggregations" instead -> http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations.html

**Comment by djtfmartin** [comment]
sounds good

**Comment by aruizca** [comment]
@djtfmartin Do you want to display all existing tags?

**Comment by djtfmartin** [comment]
yes, for now
