### ISSUE TITLE
Add mechanism to disable all notifications

### ISSUE THREAD

**Issue by aruizca** [AtlasOfLivingAustralia/taxon-overflow#19]

**Comment by djtfmartin** [comment]
We should make this a switch accessible on a user's profile page 

https://github.com/AtlasOfLivingAustralia/taxon-overflow/issues/3

**Comment by aruizca** [comment]
I would need more info to implement this. Eg:
* Should this be implemented in ala-auth
* Should we provide a ws in taxon-overflow to disable notifications for a particular user?
* If so, how do you plan to secure it
* ....

**Comment by djtfmartin** [comment]
@nickdos has made a start in a user profile page. If a user is logged in and looking at their own profile page, we should be able to let them disable alerts with a toggle switch.

Does this make sense ?

**Comment by aruizca** [comment]
The notification are internal to taxon-overflow, so I guess we would need a webservice that updates the flag in the DB. that web service should require authentication as only the user that is logged in should be allowed to change that setting.

**Comment by aruizca** [comment]
@nickdos see task #31

**Comment by nickdos** [comment]
Added to user activity page. See commit 34cac85.
