### ISSUE TITLE
Email notification support

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/taxon-overflow#2]
Add support for email notifications in taxonoverflow. 

Use cases:

- a user should received an email when someone makes an identification, comment, tag on a record they have submitted
- a user should received an email when someone makes a comment, identification on a record they have previously commented on or provided an identification 

The email should contain a link to the identification case, and a description.

**Comment by aruizca** [comment]
identification case == occurrenceId?

**Comment by djtfmartin** [comment]
identification case == question

**Comment by aruizca** [comment]
Email notifications are just for identification questions or all questions?

**Comment by djtfmartin** [comment]
all questions
