### ISSUE TITLE
Suggestion: Secure elasticsearch access

### ISSUE THREAD

**Issue by aruizca** [AtlasOfLivingAustralia/taxon-overflow#26]
At the moment the only security measure with elasticsearch is to block the 9200 port.
There is a new elastisearch add-on called [Shield](https://www.elastic.co/products/shield), that we could use to at least introduce some additional security (e.g. authentication)

**Comment by djtfmartin** [comment]
Sounds good although probably not essential for a release 1.0.
I think the elasticsearch port (9200) should be blocked by the firewall on a production CSIRO VM.
