### ISSUE TITLE
Suggestion: Integrate restapidoc plugin

### ISSUE THREAD

**Issue by aruizca** [AtlasOfLivingAustralia/taxon-overflow#30]
https://github.com/siemens/restapidoc

**Comment by djtfmartin** [comment]
For this to be of any value, we'd need to add some code to api.ala.org.au (webapi) to suck and digest the output. 
All api's need to be listed on api.ala.org.au

**Comment by aruizca** [comment]
The idea is that the API is self generated and published in a standard format: eg -> [JSONdoc](http://jsondoc.org/) or [Swagger](swagger.io)
For hat api.ala.org.au should be able to consume those formats

**Comment by djtfmartin** [comment]
Yep. Sounds good to me. I was mainly pointing out the task has 2 parts to be of any value: 
1) expose the API in the format 
2) add some code to webapi to consume that format and also mark those webservices as not editable through the webapi interface.

**Comment by aruizca** [comment]
I would be glad to do both :-)
