### ISSUE TITLE
New question with provided identification should generate answer automatically

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/taxon-overflow#37]
If users submits a sighting with the `uncertain` confidence value, then a question is automatically generated in TO. This provided identification by the user should be provided as the first answer in the question IMHO. That way an expert can simply confirm this ID by clicking the vote button.

As opposed to the current implementation where the expert has to copy/paste the name into the answer box, and then they get credit for the identification. Whereas the identification was actually made by the spotter.

**Comment by djtfmartin** [comment]
This makes a lot of sense.

**Comment by aruizca** [comment]
I don;t know how to implement this. Any clues?
