### ISSUE TITLE
The "Your activity summary" page is currently throwing error

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/taxon-overflow#39]
The "Your activity summary" page is currently dead. Assume this is a CAS config thing.
This is probably a bug with the ansible inventory but I've raised it here in case it isnt.

If the problem is with the inventory we should fix and re-run ansible.

**Comment by aruizca** [comment]
http://taxonoverflow-dev.ala.org.au/user is working for me. @nickdos Can you try please?
