### ISSUE TITLE
Ability to "star" and "unstar"  an identification case

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/taxon-overflow#4]
Add the ability to "star" and "unstar"  an identification case.
Starring an  identification case will result in that user received email alerts on comments and identifications.

**Comment by aruizca** [comment]
Can the question owner "unstar" questions? I am guessing they can't

**Comment by djtfmartin** [comment]
A general mechanism to allow users to disable all email alerts about identiications cases makes sense. Could be something a user can toggle on their user page.

https://github.com/AtlasOfLivingAustralia/taxon-overflow/issues/3

**Comment by aruizca** [comment]
They can unstar/unfollow then.

**Comment by aruizca** [comment]
More assumptions:
- The users automatically star/follow questions in the following cases:
  - The user creates a question
  - The user comments a question
  - The user comments a question answer
  - The user submits an answer 
- Any user can unstar/unfollow at any time in the question view page
- Any user can star/follow at any time in the question view page

**Comment by djtfmartin** [comment]
sounds good to me.
