### ISSUE TITLE
User profile: please review current layout

### ISSUE THREAD

**Issue by aruizca** [AtlasOfLivingAustralia/taxon-overflow#41]
I don't know how it looked before. To me there are a few obvious glitches that I don't know how to fix or whether they need to be fixed. Eg: 
![your_activity_summary](https://cloud.githubusercontent.com/assets/246477/7359649/0a2b2ffc-ed84-11e4-8a0f-70b5c49d9228.png)
In general it looks a bit rough around the edges :-)

**Comment by nickdos** [comment]
I left it a bit rough, as I thought Adam was going to have a go styling it, like he did for the other pages.
