### ISSUE TITLE
JSON Query services to allow for alert support

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/taxon-overflow#5]
This is provide a set of query services on questions that allows to retrieve a list of questions . The query service will support queries by one or more tags.

Services:

1) /ws/question/search?tags=Birds&dateCreated=2010-01-01

will return a list of questions raised after 2010-01-01 with the tag "Birds"

2) /ws/question/search?tags=Birds&comments=2010-01-01

will return a list of questions with comments that have been made after 2010-01-01 with the tag "Birds"

3) /ws/question/search?tags=Birds&identifications=2010-01-01

will return a list of questions with identifications that have been made after 2010-01-01 with the tag "Birds"

4) /ws/question/search?tags=Birds&activity=2010-01-01

will return a list of questions with identifications or comments (on questions or identifications) that have been made after 2010-01-01 with the tag "Birds"

**Comment by aruizca** [comment]
Is the date in the format year-month-day?

**Comment by nickdos** [comment]
its ISO format

**Comment by aruizca** [comment]
Does "comments" include "Answer Comments" or just "Question Comments"?

**Comment by aruizca** [comment]
when multiple tags, should all tags be present in the record or at least one of them?

**Comment by djtfmartin** [comment]
Does "comments" in #2 service include "Answer Comments" or just "Question Comments"?

>> yep

when multiple tags, should all tags be present in the record or at least one of them?

>> all
