### ISSUE TITLE
When an question has an accepted answer, if any user upvotes or downvotes the answer, the "accepted" state is lost

### ISSUE THREAD

**Issue by aruizca** [AtlasOfLivingAustralia/taxon-overflow#52]

**Comment by djtfmartin** [comment]
i dont this is a bug.

**Comment by aruizca** [comment]
Stackoverflow do not work that way. Once the answer is accepted stays that way until the owner change the status. It could be very frustrating that you mark an answer as accepted and then someone upvotes and you have to accept the answer again

**Comment by djtfmartin** [comment]
This is where we differ from stackoverflow.

The owner of the record does NOT get to decide which is the accepted answer.
This is done purely by the community votes (but we also have "Accepted Answer" button for users with a specific CAS role that we'll assign to "experts").

We decided to go this way after discussions with Mark G from Australian Museum.
