### ISSUE TITLE
Add zooming  capabilities to question list image

### ISSUE THREAD

**Issue by aruizca** [AtlasOfLivingAustralia/taxon-overflow#70]
We will also add a responsive gallery with all images

**Comment by djtfmartin** [comment]
Is it possible to use the existing image zoom capability instead of adding a new one ?

**Comment by aruizca** [comment]
You are right. Outside CSIRO some images take too much time. I think the problem is that I am using the original image instead of a thumbnail which is probably enough.

I guess the name of the task is misleading here as it is not really zooming tool cause you cannot really zoom in to see details. It is just a component to show a gallery of the available images in a more practical size (at the moment is requesting the original image) without cluttering the UI. I think the aim of the zoom viewer with tiled images is more about being able to see the details by zooming in and also to improve load times. 

Regardless of all that I think I could try and create a gallery component reusing the leaflet viewer and make it similar to how it looks in the details screen but on a floating layer. Please confirm.

**Comment by djtfmartin** [comment]
sounds good.

i've sent you messages on HipChat on this. We have a need for a generic capability to support viewing multiple images for multiple apps - see https://github.com/AtlasOfLivingAustralia/specimenbrowser/issues/10

I think we should do this just in javascript using the leaflet with leaflet controls for 2 resons: 

- support switching between images in full screen mode
- the existing tools in images-client-plugin  (subimaging, downloads, info, scaling ) are 
written in this way

**Comment by djtfmartin** [comment]
this will also be something we reuse on the identification page..
