### ISSUE TITLE
"Add an identification" dialog is confusing

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/taxon-overflow#84]
From feedback by Taryn.
If user wants to add an identification using the common name, they would sensibly type it in the common name field. This does not work! 

Instead they have to type the common name in the "scientific name" field (which has autocomplete) and then it fills in both fields, once matched.

So the UX is broken as is. Suggestion is to make it more like the pigeonhole species entry and have a single autocomplete input that once it "matches" it populates the two read-only fields of "scientific name" and "common name".
![taxonoverflow-dev_ala_org_au_question_1055](https://cloud.githubusercontent.com/assets/532845/8123746/69f0b9b4-1112-11e5-889e-cb689ddee19a.png)

**Comment by aruizca** [comment]
Can you put a snapshot of pigeonhole please?
Would it help if we put the autocomplete in both fields?
