### ISSUE TITLE
Thumbnail photo images in list page are too small

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/taxon-overflow#85]
Feedback from Taryn. After using Bower Bird and this tool, she thinks the thumbnail images are not big enough to be useful. They are much bigger on BB and she prefers this size. BB also provide a grid view which would be useful.

**Comment by aruizca** [comment]
Does she mean the thumbnails in the popup image gallery or the ones that appear in the list? 
Regarding the list thumbnails, I agree, the idea was to make them bigger but the portrait images looked terrible. Maybe I can crop the portrait images to show them as landscape. What do you guys think?

**Comment by djtfmartin** [comment]
The image-service produces several derivatives.

See http://images.ala.org.au/image/details/84422959

how about using the thumbnail_square (transparent padding), thumbnail_square_white or the thumbnail_square_darkGray

http://images.ala.org.au/store/e/2/6/4/1ea125d8-9fc0-4fb4-ae04-c1dad0d6462e/thumbnail_square

http://images.ala.org.au/store/e/2/6/4/1ea125d8-9fc0-4fb4-ae04-c1dad0d6462e/thumbnail_square_darkGray

http://images.ala.org.au/store/e/2/6/4/1ea125d8-9fc0-4fb4-ae04-c1dad0d6462e/thumbnail_square_white

**Comment by aruizca** [comment]
@ djtfmartin The problem I see is that if we keep the height to a maximum, the subject in the photo will be tiny.
If you see the thumbnails in the image gallery they all have the same height and width.  The component does that by chopping the portrait images from top and the bottom hoping that the main subject is in the middle, which happens most of the time. As a fallback you always have the image gallery to see the images clearly.
