### ISSUE TITLE
Comments on details page are confusing

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/taxon-overflow#86]
Taryn thinks the comments being both in a tab and under a provided identification are confusing to her. She was not at all clear when/where she should provide or look for comments and did not "get" the current layout.

Maybe for version 1 we should limit it to a single comments section?

**Comment by aruizca** [comment]
I agree!!

**Comment by djtfmartin** [comment]
Fine by me. Lets comment that section out for now.
