### ISSUE TITLE
Provide editable, more useful titles

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/taxon-overflow#87]
Current titles of "identification #22" are not useful.

When entry is created, app should use any provided scientific/common name as title.Failing that it should use any tags, e.g. "Unidentified Parrot, Bird". 

Title should be able to be editted by owner to be more descriptive. E.g. "Red parrot in Hughs, ACT" - suggested by Taryn.

**Comment by aruizca** [comment]
I like both ideas! 
I think it would also be useful some other way to indicate that the identification has been accepted, like by the color of the title for example.

**Comment by aruizca** [comment]
@djtfmartin Is it ok to go ahead with this? Any comments?

**Comment by djtfmartin** [comment]
+1 from me

**Comment by aruizca** [comment]
Should the title in Question be `not null`

**Comment by aruizca** [comment]
We'll make 'nullable' for the time being
